// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"
// ui_events.h is already included via ui.h, which is good.

extern void ui_event_send_start_process(); // Declared in ui.ino
extern void ui_event_send_pause_process();   // Declared in ui.ino
extern void ui_event_send_resume_process();  // Declared in ui.ino
extern void ui_event_send_stop_process();    // Declared in ui.ino

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Temperature
void ui_Temperature_screen_init(void);
void ui_event_Temperature( lv_event_t * e);
lv_obj_t *ui_Temperature;
void ui_event_Arc1( lv_event_t * e);
lv_obj_t *ui_Arc1;
lv_obj_t *ui_Label1;
lv_obj_t *ui_Label2;
// CUSTOM VARIABLES

// SCREEN: ui_Volume
void ui_Volume_screen_init(void);
void ui_event_Volume( lv_event_t * e);
lv_obj_t *ui_Volume;
void ui_event_Arc3( lv_event_t * e);
lv_obj_t *ui_Arc3;
lv_obj_t *ui_Label5;
lv_obj_t *ui_Label3;
// CUSTOM VARIABLES

// SCREEN: ui_Main_Screen
void ui_Main_Screen_screen_init(void);
void ui_event_Main_Screen( lv_event_t * e);
lv_obj_t *ui_Main_Screen;
lv_obj_t *ui_volume_;
lv_obj_t *ui_Label6;
lv_obj_t *ui_Label11;
// CUSTOM VARIABLES

// SCREEN: ui_pause
void ui_pause_screen_init(void);
void ui_event_pause( lv_event_t * e);
lv_obj_t *ui_pause;
lv_obj_t *ui_Label10;
// CUSTOM VARIABLES

// SCREEN: ui_Loading_screen
void ui_Loading_screen_screen_init(void);
lv_obj_t *ui_Loading_screen;
lv_obj_t *ui_Image1;
// CUSTOM VARIABLES

// SCREEN: ui_Hello
void ui_Hello_screen_init(void);
lv_obj_t *ui_Hello;
lv_obj_t *ui_Label4;
// CUSTOM VARIABLES

// SCREEN: ui_goodbye1
void ui_goodbye1_screen_init(void);
lv_obj_t *ui_goodbye1;
lv_obj_t *ui_Goodbye;
// CUSTOM VARIABLES

// SCREEN: ui_errors1
void ui_errors1_screen_init(void);
void ui_event_errors1_screen( lv_event_t * e); // Forward declaration
lv_obj_t *ui_errors1;
lv_obj_t *ui_errors;
// CUSTOM VARIABLES

// SCREEN: ui_Cooling_Down
void ui_Cooling_Down_screen_init(void);
void ui_event_Cooling_Down( lv_event_t * e);
lv_obj_t *ui_Cooling_Down;
lv_obj_t *ui_Spinner1;
lv_obj_t *ui_Label7;
// CUSTOM VARIABLES

// SCREEN: ui_Filling
void ui_Filling_screen_init(void);
void ui_event_Filling( lv_event_t * e);
lv_obj_t *ui_Filling;
lv_obj_t *ui_Spinner2;
lv_obj_t *ui_Label8;
// CUSTOM VARIABLES

// SCREEN: ui_ready
void ui_ready_screen_init(void);
void ui_event_ready( lv_event_t * e);
lv_obj_t *ui_ready;
lv_obj_t *ui_Spinner3;
lv_obj_t *ui_Label9;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Temperature( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Main_Screen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Main_Screen_screen_init);
}
}

void ui_event_Arc1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_arc_set_text_value( ui_Label2, target, "", "");
      // CUSTOM CODE START
      ui_event_send_temperature_setpoint(lv_arc_get_value(target));
      // CUSTOM CODE END
}
}

void ui_event_Volume( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( &ui_Main_Screen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Main_Screen_screen_init);
}
}

void ui_event_Arc3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_arc_set_text_value( ui_Label3, target, "", "");
      // CUSTOM CODE START
      ui_event_send_volume_setpoint(lv_arc_get_value(target));
      // CUSTOM CODE END
}
}

void ui_event_Main_Screen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target_obj = lv_event_get_target(e); // Get the object that triggered the event

    if (target_obj == ui_Label11) { // Event specifically for the "Start" label
        if (event_code == LV_EVENT_CLICKED || (event_code == LV_EVENT_KEY && lv_event_get_key(e) == LV_KEY_ENTER)) {
            ui_event_send_start_process();
        }
    } else if (target_obj == ui_Main_Screen) { // Events for the screen background itself
        if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change( &ui_Volume, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Volume_screen_init);
        }
        if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change( &ui_Temperature, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Temperature_screen_init);
        }
        if ( event_code == LV_EVENT_LONG_PRESSED) {
            ui_event_send_pause_process();
            _ui_screen_change( &ui_pause, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_pause_screen_init);
        }
    }
}

void ui_event_pause( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    // If the screen itself is clicked or encoder pressed
    if (event_code == LV_EVENT_CLICKED || (event_code == LV_EVENT_KEY && lv_event_get_key(e) == LV_KEY_ENTER)) {
        ui_event_send_resume_process();
      // Screen change will be handled by status update from main ESP32
      // For immediate feedback, you could switch to Main_Screen or a "Resuming..." screen here
      // _ui_screen_change( &ui_Main_Screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Main_Screen_screen_init);
    }
    if (event_code == LV_EVENT_LONG_PRESSED) { // Optional: long press to go back without resuming
        _ui_screen_change( &ui_Main_Screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Main_Screen_screen_init);
    }
}

void ui_event_Cooling_Down( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_LONG_PRESSED) {
      _ui_screen_change( &ui_Main_Screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Main_Screen_screen_init);
}
}

void ui_event_Filling( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_LONG_PRESSED) {
      _ui_screen_change( &ui_Main_Screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Main_Screen_screen_init);
}
}

void ui_event_ready( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_LONG_PRESSED) {
      _ui_screen_change( &ui_Main_Screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Main_Screen_screen_init);
}
}

void ui_event_errors1_screen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
    if (event_code == LV_EVENT_CLICKED || (event_code == LV_EVENT_KEY && lv_event_get_key(e) == LV_KEY_ENTER)) {
        ui_event_send_stop_process(); // Or CMD_ACK_ERROR
        // Main ESP32 should update state to IDLE, which will trigger screen change
        // _ui_screen_change( &ui_Main_Screen, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Main_Screen_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Temperature_screen_init();
ui_Volume_screen_init();
ui_Main_Screen_screen_init();
  if (ui_Label11) { 
      lv_obj_add_flag(ui_Label11, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_FOCUSABLE);
  }
ui_pause_screen_init();
ui_Loading_screen_screen_init();
ui_Hello_screen_init();
ui_goodbye1_screen_init();
ui_errors1_screen_init();
ui_Cooling_Down_screen_init();
ui_Filling_screen_init();
ui_ready_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
  if (ui_errors1) {
    lv_obj_add_event_cb(ui_errors1, ui_event_errors1_screen, LV_EVENT_ALL, NULL);
  }
lv_disp_load_scr( ui_Loading_screen);
}
