// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Temperature
void ui_Temperature_screen_init(void);
void ui_event_Temperature( lv_event_t * e);
extern lv_obj_t *ui_Temperature;
void ui_event_Arc1( lv_event_t * e);
extern lv_obj_t *ui_Arc1;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Label2;
// CUSTOM VARIABLES

// SCREEN: ui_Volume
void ui_Volume_screen_init(void);
void ui_event_Volume( lv_event_t * e);
extern lv_obj_t *ui_Volume;
void ui_event_Arc3( lv_event_t * e);
extern lv_obj_t *ui_Arc3;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_Label3;
// CUSTOM VARIABLES

// SCREEN: ui_Main_Screen
void ui_Main_Screen_screen_init(void);
void ui_event_Main_Screen( lv_event_t * e);
extern lv_obj_t *ui_Main_Screen;
extern lv_obj_t *ui_volume_;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_Label11;
// CUSTOM VARIABLES

// SCREEN: ui_pause
void ui_pause_screen_init(void);
void ui_event_pause( lv_event_t * e);
extern lv_obj_t *ui_pause;
extern lv_obj_t *ui_Label10;
// CUSTOM VARIABLES

// SCREEN: ui_Loading_screen
void ui_Loading_screen_screen_init(void);
extern lv_obj_t *ui_Loading_screen;
extern lv_obj_t *ui_Image1;
// CUSTOM VARIABLES

// SCREEN: ui_Hello
void ui_Hello_screen_init(void);
extern lv_obj_t *ui_Hello;
extern lv_obj_t *ui_Label4;
// CUSTOM VARIABLES

// SCREEN: ui_goodbye1
void ui_goodbye1_screen_init(void);
extern lv_obj_t *ui_goodbye1;
extern lv_obj_t *ui_Goodbye;
// CUSTOM VARIABLES

// SCREEN: ui_errors1
void ui_errors1_screen_init(void);
extern lv_obj_t *ui_errors1;
extern lv_obj_t *ui_errors;
// CUSTOM VARIABLES

// SCREEN: ui_Cooling_Down
void ui_Cooling_Down_screen_init(void);
void ui_event_Cooling_Down( lv_event_t * e);
extern lv_obj_t *ui_Cooling_Down;
extern lv_obj_t *ui_Spinner1;
extern lv_obj_t *ui_Label7;
// CUSTOM VARIABLES

// SCREEN: ui_Filling
void ui_Filling_screen_init(void);
void ui_event_Filling( lv_event_t * e);
extern lv_obj_t *ui_Filling;
extern lv_obj_t *ui_Spinner2;
extern lv_obj_t *ui_Label8;
// CUSTOM VARIABLES

// SCREEN: ui_ready
void ui_ready_screen_init(void);
void ui_event_ready( lv_event_t * e);
extern lv_obj_t *ui_ready;
extern lv_obj_t *ui_Spinner3;
extern lv_obj_t *ui_Label9;
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_2013798505);   // assets/bere-spumanti-logo-full@480.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
