// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Cooling_Down_screen_init(void)
{
ui_Cooling_Down = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Cooling_Down, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Spinner1 = lv_spinner_create(ui_Cooling_Down,1000,90);
lv_obj_set_width( ui_Spinner1, 420);
lv_obj_set_height( ui_Spinner1, 420);
lv_obj_set_align( ui_Spinner1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Spinner1, LV_OBJ_FLAG_CLICKABLE );    /// Flags

lv_obj_set_style_arc_color(ui_Spinner1, lv_color_hex(0x990000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Spinner1, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_Label7 = lv_label_create(ui_Cooling_Down);
lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label7, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label7,"Cooling Down");
lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Cooling_Down, ui_event_Cooling_Down, LV_EVENT_ALL, NULL);

}
