// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_errors1_screen_init(void)
{
ui_errors1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_errors1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_errors = lv_obj_create(ui_errors1);
lv_obj_set_width( ui_errors, 350);
lv_obj_set_height( ui_errors, 300);
lv_obj_set_align( ui_errors, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_errors, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

}
