// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Filling_screen_init(void)
{
ui_Filling = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Filling, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Spinner2 = lv_spinner_create(ui_Filling,1000,90);
lv_obj_set_width( ui_Spinner2, 420);
lv_obj_set_height( ui_Spinner2, 420);
lv_obj_set_align( ui_Spinner2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Spinner2, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_obj_set_style_arc_width(ui_Spinner2, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_Spinner2, lv_color_hex(0xA18B1F), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Spinner2, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_Spinner2, 10, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_Label8 = lv_label_create(ui_Filling);
lv_obj_set_width( ui_Label8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label8, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label8,"Filling");
lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Filling, ui_event_Filling, LV_EVENT_ALL, NULL);

}
