// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_goodbye1_screen_init(void)
{
ui_goodbye1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_goodbye1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Goodbye = lv_label_create(ui_goodbye1);
lv_obj_set_width( ui_Goodbye, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Goodbye, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Goodbye, LV_ALIGN_CENTER );
lv_label_set_text(ui_Goodbye,"Bye");
lv_obj_set_style_text_font(ui_Goodbye, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

}
