// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Main_Screen_screen_init(void)
{
ui_Main_Screen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Main_Screen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_volume_ = lv_label_create(ui_Main_Screen);
lv_obj_set_width( ui_volume_, LV_SIZE_CONTENT);  /// 120
lv_obj_set_height( ui_volume_, LV_SIZE_CONTENT);   /// 100
lv_obj_set_x( ui_volume_, 150 );
lv_obj_set_y( ui_volume_, 50 );
lv_obj_set_align( ui_volume_, LV_ALIGN_CENTER );
lv_label_set_text(ui_volume_,"vol");
lv_obj_set_style_text_font(ui_volume_, &lv_font_montserrat_36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label6 = lv_label_create(ui_Main_Screen);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 120
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 100
lv_obj_set_x( ui_Label6, -150 );
lv_obj_set_y( ui_Label6, 50 );
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6,"temp");
lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label11 = lv_label_create(ui_Main_Screen);
lv_obj_set_width( ui_Label11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label11, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label11,"Start");
lv_obj_add_flag( ui_Label11, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_FOCUSABLE );    /// Flags
lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Main_Screen, ui_event_Main_Screen, LV_EVENT_ALL, NULL);

}
