// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_ready_screen_init(void)
{
ui_ready = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ready, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Spinner3 = lv_spinner_create(ui_ready,1000,90);
lv_obj_set_width( ui_Spinner3, 420);
lv_obj_set_height( ui_Spinner3, 420);
lv_obj_set_align( ui_Spinner3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Spinner3, LV_OBJ_FLAG_CLICKABLE );    /// Flags

lv_obj_set_style_arc_color(ui_Spinner3, lv_color_hex(0x0A661D), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Spinner3, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_Spinner3, true, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_Label9 = lv_label_create(ui_ready);
lv_obj_set_width( ui_Label9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label9, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label9,"Ready");
lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_ready, ui_event_ready, LV_EVENT_ALL, NULL);

}
