// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Volume_screen_init(void)
{
ui_Volume = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Volume, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Arc3 = lv_arc_create(ui_Volume);
lv_obj_set_width( ui_Arc3, 420);
lv_obj_set_height( ui_Arc3, 420);
lv_obj_set_align( ui_Arc3, LV_ALIGN_CENTER );
lv_arc_set_range(ui_Arc3, 50,500);
lv_arc_set_value(ui_Arc3, 5);

ui_Label5 = lv_label_create(ui_Arc3);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label5, 0 );
lv_obj_set_y( ui_Label5, 190 );
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label5,"ML");
lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label3 = lv_label_create(ui_Arc3);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"125");
lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Arc3, ui_event_Arc3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Volume, ui_event_Volume, LV_EVENT_ALL, NULL);

}
